name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verficação de versão
      run:  lsb_release -a && gcc -v && bash -version
    - name: solucao
      run:  ls /usr/bin/expect && sudo apt-get install -y gcovr && sudo apt-get install expect && gcc -ftest-coverage -g3 solucao.c -o solucao && ls && chmod +x solucao.sh && bash -x solucao.sh && gcov solucao.c
